---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-metallb-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.8.40-192.168.8.45
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-metallb-l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - default-metallb-ip-pool
