---
- name: "Setup keepalived and haproxy"
  hosts: masters
  become: true
  tasks:

    - name: "Copy keepalived conf file"
      ansible.builtin.copy:
        src: ./files/keepalived/keepalived.conf
        dest: /etc/keepalived/keepalived.conf
        owner: root
        group: root
        mode: '0644'
        backup: true
      notify:
        - "Restart keepalived"

    - name: "Copy keepalived script for API check"
      ansible.builtin.copy:
        src: ./files/keepalived/check_apiserver.sh
        dest: /etc/keepalived/check_apiserver.sh
        owner: root
        group: root
        mode: '0755'
        backup: true
      notify:
        - "Restart keepalived"

    - name: "Copy haproxy config file"
      ansible.builtin.copy:
        src: ./files/haproxy/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: '0755'
        backup: true
      notify:
        - "Restart haproxy"

    - name: "Ensure that keepalived is started"
      ansible.builtin.systemd_service:
        state: started
        enabled: true
        name: keepalived

    - name: "Ensure that haproxy is started"
      ansible.builtin.systemd_service:
        state: started
        enabled: true
        name: haproxy


  handlers:
    - name: "Restart keepalived"
      become: true
      ansible.builtin.systemd_service:
        state: restarted
        enabled: true
        name: keepalived

    - name: "Restart haproxy"
      become: true
      ansible.builtin.systemd_service:
        state: restarted
        enabled: true
        name: haproxy
